name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-xcode-12:
    env:
      DEVELOPER_DIR: /Applications/Xcode_12_beta.app/Contents/Developer


    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
    - name: Run Xcode 12 tests
      run: xcodebuild test -scheme AppStorage-Package -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.0'

  test-xcode-11:
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.6.app/Contents/Developer


    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run Xcode 11 tests
      run: swift test
